Make deploy-rpms more scp friendly.

diff --git a/linux/deploy-rpms b/linux/deploy-rpms
--- a/linux/deploy-rpms
+++ b/linux/deploy-rpms
@@ -56,7 +56,7 @@ function Usage
 	usage+="[-a arch] [-c] [-f] [-r repo] [-R] [-s os] [-T _topdir] [-v] "
 	usage+="[RPM ...]\n\n"
 	usage+="    -a arch		Architecture\n"
-	usage+="    -c			Use scp for deploying instead of curl\n"
+	usage+="    -c			Use curl for deploying instead of scp\n"
 	usage+="    -f			Treat topdir as a flat directory\n"
 	usage+="    -R			Release to artifactory\n"
 	usage+="    -r repo		Repo <${!Repos[@]}> "
@@ -194,50 +194,47 @@ function FilterRpms
 }
 
 
-function DeployFile
-{
-	local file=$1
-	local sha1=$2
-	local url=$3
-	local rsha1
-
-	if rsha1=$(curl -fs -u "anonymous:" "$url.sha1")
-	then
-		[[ "$rsha1" != "$sha1" ]] || { echo "skipped"; return; }
-	fi
-
-	if (( Flag_c ))
-	then
-		copy -P 4443 "$file" \
-			artifactory-ssh-proxy.corp.yahoo.com:${url#$BaseRepoURL}
-	else
-		curl -fsS -i -X PUT \
-			-u "$DeployerAccount:$DeployerPassword" \
-			-H "X-Checksum-Sha1: $sha1" \
-			-T "$file" \
-			"$url" > /dev/null && echo "success" || echo "failed"
-	fi
-}
-
-
 function DeployRpms
 {
 	local repourl=$1; shift
-	local f
+	local scpdir=$1; shift
+	local f loc
 
 	for f in "$@"
 	do
 		local sha1=$(sha1sum "$f" | awk '{print $1}') || \
 			Fatal "Cannot determine sha1 of '$f'."
-		local url="$repourl/${f##*/}"
+		local url=$repourl/${f##*/}
+		local rsha1=$(curl -fs -u "anonymous:" "$url.sha1")
 
-		case $(DeployFile "$f" "$sha1" "$url") in
-		"success") (( !Verbose )) || \
-			echo "Deployed file '$f' to '$url'.";;
-		"skipped") (( !Verbose )) || \
-			echo "Skipped '$f': already deployed to '$url'.";;
-		*) Fatal "Failed to deploy file '$f' to '$url'.";;
-		esac
+		if [[ "$rsha1" == "$sha1" ]]
+		then
+			(( !Verbose )) || \
+				echo "Skipped '$f': already deployed to '$url'."
+			continue
+		fi
+
+		if (( Flag_c ))
+		then
+			loc=$url
+			curl -fsS -i -X PUT \
+				-u "$DeployerAccount:$DeployerPassword" \
+				-H "X-Checksum-Sha1: $sha1" \
+				-T "$f" \
+				"$url" > /dev/null
+		else
+			local scppath="$scpdir/${f##*/}"
+			loc=$scppath
+			scp -P 4443 -- "$f" "$scppath"
+		fi
+
+		if (( $? == 0 ))
+		then
+			(( !Verbose )) || \
+				echo "Deployed file '$f' to '$loc'."
+		else
+			Fatal "Failed to deploy file '$f' to '$loc'."
+		fi
 	done
 }
 
@@ -254,7 +251,7 @@ declare -i Flag_c=0 Flag_f=0 Flag_R=0
 declare -i Verbose=0
 declare opt
 declare DeployerAccount=lkt_deployer_headless
-declare BaseRepoURL
+declare BaseRepoURL BaseRepoScp
 
 declare -A Repos
 Repos=([stable]=1 [current]=1 [test]=1 [quarantine]=1)
@@ -302,11 +299,13 @@ fi
 if (( Flag_R ))
 then
 	BaseRepoURL=http://artifactory.ops.yahoo.com:9999/artifactory
+	BaseRepoScp=artifactory-ssh-proxy.corp.yahoo.com
 else
 	BaseRepoURL=http://test.artifactory.corp.yahoo.com:9999/artifactory
+	BaseRepoScp=stg-artifactory-ssh-proxy-01.infra.corp.bf1.yahoo.com
 fi
 
-if (( !Flag_c ))
+if (( Flag_c ))
 then
 	[[ -n ${DeployerPassword-} ]] || \
 		Fatal "Environment variable '\$DeployerPassword' is not set."
@@ -335,14 +334,17 @@ esac
 (( !${#SrcRpms[@]} )) || \
 	DeployRpms \
 		"$BaseRepoURL/lkt-yum/$Os/$Repo/Source/Packages" \
+		"$BaseRepoScp:/lkt-yum/$Os/$Repo/Source/Packages" \
 		"${SrcRpms[@]}"
 
 (( !${#DbgRpms[@]} )) || \
 	DeployRpms \
 		"$BaseRepoURL/lkt-yum/$Os/$Repo/$Arch-debug/Packages" \
+		"$BaseRepoScp:/lkt-yum/$Os/$Repo/$Arch-debug/Packages" \
 		"${DbgRpms[@]}"
 
 (( !${#BinRpms[@]} )) || \
 	DeployRpms \
 		"$BaseRepoURL/lkt-yum/$Os/$Repo/$Arch/Packages" \
+		"$BaseRepoScp:/lkt-yum/$Os/$Repo/$Arch/Packages" \
 		"${BinRpms[@]}"
